version: '3'

services:
  db:
    image: postgres:9.6-alpine
    hostname: db
    env_file:
      - config/.envfile
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: web
    command: bash -c "python manage.py collectstatic --noinput && gunicorn project.wsgi:application --workers 3 --bind unix:/app/project.sock"
    volumes:
      - ./src:/app
    env_file:
      - config/.envfile
    links:
      - db
    depends_on:
      - db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./src:/app
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  db-data: