version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=project
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=project
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
